name = "my-money-api"
compatibility_date = "2023-01-01"
send_metrics = false
main="src/index.ts"
account_id = "11d57fc90d69f90b74b10ec0e285ab97"

[vars]
INTERACTIVE_BROKERS_FLEX_DIVIDENDS_QUERY_ID = "562376"

# Secrets
# INTERACTIVE_BROKERS_FLEX_WEB_TOKEN