name: buildAndDeployWorker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: npm ci

      - name: Deploy
        run: |
          echo '${{ secrets.CLOUDFLARE_API_TOKEN }}'
          echo $CLOUDFLARE_API_TOKEN
          npm run deploy
        env:
          CLOUDFLARE_API_TOKEN: '${{ secrets.CLOUDFLARE_API_TOKEN }}' 